### ISSUE TITLE
部署本项目到cn服务器，替换掉workflow

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-saas#2]
上线流程：
- [x] 停掉nginx服务
- [x] 停掉现有apps服务
- [x] 备份数据库
- [x] 调整nginx配置
- [x] 项目下新建并配置.env.local文件
- [x] 调整docker-compose.yml，增加primary和secondary配置，steedos-config-primary.yml，steedos-config-secondary.yml, 并且将workflow的settings迁移到saas
- [x] 检查settings是否有重复及确认同样的settings是否表示不同的功能，如果表示不同功能则有冲突，需处理
- [x] 通过workflow的提交记录检查creator中workflow代码和workflow代码差异
- [x] 去掉自动导入模板流程功能 #19: 通过删除配置文件中的workflowTemplates属性来处理: workflow的配置文件及creator的配置文件
- [x] [CMS应用上线前考虑之前的附件写脚本兼容新的二合一版本](https://github.com/steedos/creator/issues/1609)
- [x] [新增开关 tenant.saas = true 表示云版，否则就是落地版。](https://github.com/steedos/object-server/issues/213) , 云版本需要配置上tenant.saas=true，否则不生效
- [x] 密码方式登录要开启，配置文件中tenant.enable_password_login 设置为true
- [x] 云平台需要在配置文件中添加templateSpaceId(5e38d51b41386900110ff5c5)， [cloudAdminSpaceId](https://github.com/steedos/object-server/issues/242) 
- [x] 项目根目录下新建.migrate文件，只启用primary服务
```js
// open nodejs console 
process.env.MONGO_URL="mongodb://172.17.5.127:27017/steedos"
var migrate = require("@steedos/migrate");
migrate.up();
```
- [x] 写个mongo 脚本， 把user的phone字段清空，这个mongo脚本必须在 migrate 脚本之后执行。
```js
db.getCollection('users').update({phone: {$exists: true}}, {$unset: { phone: 1}}, {multi: true})
```
- [x] 启用secondary服务
- [x] 启用nginx

**Comment by sunhaolin** [comment]
涉及升级脚本及配置：
- [ ] 去掉自动导入模板流程功能 #19: 通过删除配置文件中的workflowTemplates属性来处理: workflow的配置文件及creator的配置文件
- [ ] [CMS应用上线前考虑之前的附件写脚本兼容新的二合一版本](https://github.com/steedos/creator/issues/1609)
- [ ] 配置auto_migrate: true，执行新的内核升级脚本，[user, space_user 数据结构及功能调整](https://github.com/steedos/steedos-accounts/issues/44)
- [ ] [新增开关 tenant.saas = true 表示云版，否则就是落地版。](https://github.com/steedos/object-server/issues/213) , 云版本需要配置上tenant.saas=true，否则不生效

**Comment by sunhaolin** [comment]
- [ ] 二合一中Meteor.settings.cron.instancerecordqueue_interval冲突
